# Generated by Django 3.0.2 on 2020-02-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200122_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
