# Generated by Django 3.0.2 on 2020-01-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, default='category-url', unique=True),
        ),
        migrations.AddField(
            model_name='product_type',
            name='type_slug',
            field=models.SlugField(blank=True, default='type-url', unique=True),
        ),
    ]
