# Generated by Django 3.0.2 on 2020-01-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20200120_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='type_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
