# Generated by Django 3.0.2 on 2020-01-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20200120_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='type_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
