# Generated by Django 3.0.2 on 2020-01-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_profile',
            fields=[
                ('brand_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_logo', models.ImageField(upload_to='brand/logo/%Y/%m/%d/')),
                ('brand_logo_alt_text', models.CharField(max_length=255)),
                ('brand_info', models.TextField()),
                ('brand_description', models.CharField(max_length=255)),
                ('brand_country', models.CharField(default='global', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Brand')),
            ],
            options={
                'db_table': 'brand_profile',
            },
        ),
    ]
