# Generated by Django 3.0.2 on 2020-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='global', max_length=255),
        ),
    ]
