# Generated by Django 3.0.2 on 2020-01-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_auto_20200123_1502'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
