# Generated by Django 3.0.2 on 2020-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_auto_20200123_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_profile',
            name='brand_title',
            field=models.CharField(default='brand', max_length=255),
        ),
    ]
