# Generated by Django 3.0.2 on 2020-01-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_brand_profile_brand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_profile',
            name='brand_country',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='myadmin.Country'),
        ),
    ]
