# Generated by Django 3.0.2 on 2020-01-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0020_auto_20200124_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_profile',
            name='brand_status',
            field=models.CharField(default='publish', max_length=100),
        ),
    ]
