# Generated by Django 3.0.2 on 2020-01-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0022_auto_20200125_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
