# Generated by Django 3.0.2 on 2020-01-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0023_auto_20200125_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
