# Generated by Django 3.0.2 on 2020-01-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0025_auto_20200130_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_profile',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='brand_profile',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='brand_profile',
            old_name='country_id',
            new_name='country',
        ),
    ]
