# Generated by Django 3.0.2 on 2020-01-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0026_auto_20200130_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_description',
            field=models.CharField(default='publish', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_info',
            field=models.TextField(default='publish'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(default='publish', upload_to='brand/logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_logo_alt_text',
            field=models.CharField(default='publish', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_status',
            field=models.CharField(default='publish', max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_title',
            field=models.CharField(default='publish', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='myadmin.Country'),
        ),
        migrations.DeleteModel(
            name='Brand_profile',
        ),
    ]
