# Generated by Django 3.0.2 on 2020-01-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0027_auto_20200130_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(upload_to='brand/logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo_alt_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_title',
            field=models.CharField(max_length=255),
        ),
    ]
