# Generated by Django 3.0.2 on 2020-01-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0028_auto_20200130_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(upload_to='brand/logo/%Y/%m/'),
        ),
    ]
