# Generated by Django 3.0.2 on 2020-02-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0029_auto_20200130_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=255)),
                ('feature_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Product_type')),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('product_info', models.TextField()),
                ('product_description', models.CharField(max_length=255)),
                ('product_starting_price', models.CharField(max_length=255)),
                ('product_status', models.CharField(default='publish', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Brand')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Product_type')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Product_feature',
            fields=[
                ('product_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Feature')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Product')),
            ],
            options={
                'db_table': 'product_feature',
            },
        ),
    ]
