# Generated by Django 3.0.2 on 2020-02-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0030_feature_product_product_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_feature',
            old_name='feature_id',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='product_feature',
            old_name='product_id',
            new_name='product',
        ),
    ]
