# Generated by Django 3.0.2 on 2020-02-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0032_auto_20200203_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='feature_product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Product_type',
        ),
    ]
