# Generated by Django 3.0.2 on 2020-02-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0033_auto_20200204_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('product_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type_name', models.CharField(max_length=255, unique=True)),
                ('product_type_description', models.TextField()),
                ('product_type_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Category')),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Product_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Product_type'),
        ),
    ]
