# Generated by Django 3.0.2 on 2020-02-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0038_remove_feature_feature_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Category'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='myadmin.Category'),
        ),
    ]
