# Generated by Django 3.0.2 on 2020-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0039_auto_20200206_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_type',
            name='product_type_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
