# Generated by Django 3.0.2 on 2020-02-16 10:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0041_auto_20200216_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
