# Generated by Django 3.0.2 on 2020-02-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0042_auto_20200216_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='feature_product_type',
            new_name='feature_category_type',
        ),
    ]
