# Generated by Django 3.0.2 on 2020-02-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0046_auto_20200216_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='feature_product_type',
            new_name='product_type',
        ),
    ]
