# Generated by Django 3.0.2 on 2020-02-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0048_auto_20200218_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('seen', 'Seen'), ('replied', 'Replied'), ('completed', 'Completed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
