# Generated by Django 3.0.2 on 2020-02-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0051_auto_20200218_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_item_id', models.IntegerField(null=True)),
                ('review_item_type', models.CharField(max_length=10)),
                ('features_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value_for_money_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ease_of_use_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_support_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review', models.CharField(max_length=50000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
