# Generated by Django 3.0.2 on 2020-02-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0052_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_item_type',
            field=models.CharField(choices=[('brand', 'Brand'), ('product', 'Product')], max_length=10),
        ),
    ]
