# Generated by Django 3.0.2 on 2020-02-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0053_auto_20200218_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
