# Generated by Django 3.0.2 on 2020-02-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0054_remove_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='status',
            new_name='review_status',
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
