# Generated by Django 3.0.2 on 2020-02-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0056_auto_20200220_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer_support_rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='ease_of_use_rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='features_rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_for_money_rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
