# Generated by Django 3.0.2 on 2020-02-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0058_auto_20200222_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_feature',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_features', to='myadmin.Product'),
        ),
    ]
