# Generated by Django 3.0.2 on 2020-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0059_auto_20200222_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_subscription',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
