# Generated by Django 3.0.2 on 2020-02-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0060_product_product_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_subscription',
            field=models.CharField(choices=[('m', 'Month'), ('y', 'Year')], max_length=1),
        ),
    ]
