# Generated by Django 3.0.2 on 2020-02-25 11:19

from django.db import migrations, models
import django.db.models.deletion
import myadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0062_auto_20200224_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertHelp',
            fields=[
                ('help_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=10)),
                ('customer_note', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('seen', 'Seen'), ('replied', 'Replied'), ('completed', 'Completed')], max_length=10)),
                ('customer_inquiry_page_url', models.CharField(max_length=200)),
                ('ticket_code', models.IntegerField(default=myadmin.models.ExpertHelp.ticket_number, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_coutry', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='myadmin.Country')),
                ('customer_help_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='myadmin.Category')),
            ],
            options={
                'db_table': 'expert_help',
            },
        ),
    ]
