# Generated by Django 3.0.2 on 2020-03-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0065_auto_20200308_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='user',
        ),
    ]
