# Generated by Django 3.0.2 on 2020-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0068_auto_20200314_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
