# Generated by Django 3.0.2 on 2020-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0069_product_product_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
