# Generated by Django 3.0.2 on 2020-03-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0072_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price_currency',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='myadmin.Currency'),
        ),
    ]
