# Generated by Django 3.0.2 on 2020-06-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0074_auto_20200316_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experthelp',
            name='customer_help_category',
        ),
        migrations.AddField(
            model_name='experthelp',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.Category'),
        ),
    ]
