from django.urls import path
from myadmin import views

urlpatterns = [
    path('',views.index),
    path('admin_auth/',views.admin_auth),
    path('dashboard/',views.dashboard),
    path('logout/',views.logout),
    path('setting/',views.setting),
    path('admin_info_update/',views.admin_info_update),
    path('category/',views.category),
    path('add_category/',views.add_category),
    path('category/delete/',views.category_delete),
    path('product-type/',views.product_type),
    path('product-type/delete/',views.product_type_delete),
    path('add_product_type/',views.add_product_type),
    path('add_brand/',views.brand),
    path('save_brand/',views.add_brand),
    path('brand/',views.show_brand),
    path('brand/delete/',views.brand_delete),
    path('feature/',views.feature),
    path('feature/delete/',views.feature_delete),
    path('add_feature/',views.add_feature),
    path('product/',views.product),
    path('new-product/',views.new_product),
    path('add_product/',views.add_product),
    path('product/delete/',views.product_delete),
    path('product/features/<slug:product_id>/',views.edit_features),
    path('inquiries/',views.inquiries),
    path('inquiries/reply/<slug:contact_id>/',views.inquiry_reply),
    path('inquiries/reply-send/',views.inquiry_reply_send),
    path('inquiries/delete/',views.inquiry_delete),
    path('user/',views.show_user),
    path('user/delete/',views.user_delete),
    path('generate-users-pdf/',views.generate_user_pdf, name="generate_user_pdf"),
    path('category/edit/<slug:category_id>/',views.edit_category),
    path('category/update/',views.update_category),
    path('product-type/edit/<slug:product_type_id>/',views.edit_product_type),
    path('product-type/update/',views.update_product_type),
    path('feature/edit/<slug:feature_id>/',views.edit_feature),
    path('feature/update/',views.update_feature),
    path('brand/edit/<slug:brand_id>/',views.edit_brand),
    path('brand/update/',views.update_brand),
    path('product/edit/<slug:product_id>/',views.edit_product),
    path('product/update/',views.update_product),
    path('expert-help-tickets/',views.expert_help_inquiries),
    path('expert-help-tickets/reply/<slug:help_id>/',views.expert_help_reply),
    path('expert-help-tickets/reply-send/',views.expert_help_reply_send),
    path('expert-help-tickets/delete/',views.expert_help_inquiry_delete),
    path('review/',views.pending_reviews),
    path('review/delete/',views.review_delete),
    path('review/approve/<slug:review_id>/',views.review_approve),
    path('review/approved/',views.approved_reviews),

]
